# ---------- Default Configuration ----------- #
baseURL = "https://cephaloniahouses.eu/"
title = "Chrysanthi Thomatou"
theme = "port-hugo"



# ----------------- Plugins ----------------- #
# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"



# ---------------- Navigation ---------------- #
# main menu
[[menu.main]]
name = "Education"
URL = "#about"
weight = 1

[[menu.main]]
name = "Seminars"
URL = "#portfolio"
weight = 2

[[menu.main]]
name = "Contact"
URL = "#contact"
weight = 3



# ------------ Deafualt Parameters ------------ #
[params]
logo_light = "images/logo-blue.png"
logo_dark = "images/x-dark.svg"
copyright = "Powered by Fotis Valsamos | Copyright Chrysanthi Thomatou &copy;"
# Meta data
description = "Personal Website"
author = "Fotis Valsamos"
favicon = "images/x-dark.png"
google_analytics = "G-ABCDEFG123"


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif"



# ------------------ Social ------------------ #
[[params.social]]
icon = "fa fa-envelope"
link = "mailto:cthomatou01@gmail.com"

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/chrysanthi-thomatou-33a747209/"

contentDir = "content/english"
weight = 1
home = "Home"